### ISSUE TITLE
Remove any code that is related to obstacles from scripts.

### ISSUE THREAD

**Issue by rafiiary** [kawaitenshi/foolsrun#111]

**Comment by kawaitenshi** [comment]
We later discussed just commenting out the code and maybe making the obstacles deduct from score rather than making the player fall.

**Comment by rafiiary** [comment]
I don't know what "deduct from score" even means. What score are we keeping?

**Comment by kawaitenshi** [comment]
We discussed it after you left the meeting that day. We're planning to ideally implement a scoring system based on how many gems the player collected and how quickly the player finished each level (how much time was remaining when the player finished the level). The score is supposed to build up throughout the game (not limited to one level). Magda suggested we deduct from score when a player hits an obstacle rather than removing obstacles altogether since the obstacles are there already.

**Comment by rafiiary** [comment]
Okay who's implementing this?
